version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    container_name: laravel_app
    restart: always
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    environment:
      - DB_HOST=mysql
      - QUEUE_CONNECTION=redis
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
    depends_on:
      - mysql
      - redis
    networks:
      - laravel_network

  mysql:
    image: mysql:latest
    container_name: laravel_mysql
    restart: always
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - laravel_network

  redis:
    image: redis:alpine
    container_name: laravel_redis
    restart: always
    networks:
      - laravel_network

  # Add php-fpm and nginx services as needed (not shown here for brevity)

volumes:
  mysql_data:

networks:
  laravel_network:
    driver: bridge
